data:extend{
  {
    type = "item",
    name = "button",
    icon = "__manual-control__/graphics/button/pushbutton-icon.png",
    icon_size = 32,
    subgroup = "circuit-network",
    place_result="button",
    order = "b[combinators]-d[manual-control]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "switch",
    icon = "__manual-control__/graphics/button/pushbutton-icon.png",
    icon_size = 32,
    subgroup = "circuit-network",
    place_result="switch",
    order = "b[combinators]-d[manual-control]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "passthrough-button",
    icon = "__manual-control__/graphics/button/pushbutton-icon.png",
    icon_size = 32,
    subgroup = "circuit-network",
    place_result="passthrough-button",
    order = "b[combinators]-d[manual-control]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "passthrough-switch",
    icon = "__manual-control__/graphics/button/pushbutton-icon.png",
    icon_size = 32,
    subgroup = "circuit-network",
    place_result="passthrough-switch",
    order = "b[combinators]-d[manual-control]",
    stack_size = 50,
  },
  }
